### ISSUE TITLE
PLAYTESTING

### ISSUE THREAD

**Issue by EimantasGag** [LightPunderland/ReflexSharp-FE#3]
Reikia surasti geriausias values konstantoms su kuriomis fizikos zaidimos jauciasi geriausiai. Tai reikia values situ konstantu: 
 
**MovementMomentum klase:** `momentumMaxTime`, `initialMomentumTime`, `momentumLoseRate`
**MovementPhysics klase:** `maxSpeed`
**MovementPhysics klase:** `maxSpeed`
**main.js faile:** `reduceDiagonalSpeed`

Tai tipo galit cia komentara parasyt su values kokios jums atrodo geriausios arba galit brancha nauja papushinti playtesting-values ar kazka tokio.

**Comment by lukasja111** [comment]
Old issue.
Resolved(ish).
